---
title: "First blog post"
date: 2018-9-18
---

title: Software Developer
author: sunny-aguilar
email: sunny.aguilar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Sunny and I'm a student at OSU studying computer science.

# social links
twitter_username: sunny-agui
github_username:  sunny-aguilar

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

